name: roviweb
channels:
  - defaults
  - conda-forge
dependencies:
  # Core dependencies
  - python==3.11.*
  - fastapi==0.115.*
  - python-duckdb
  - uvicorn

  # Testing
  - pytest

  # Dependencies for projects not yet on conda
  - pip
  - pip:
      - jupyterlab
      - -e .[test]
